### ISSUE TITLE
Unable to grab data from global text field

### ISSUE THREAD

**Issue by workplaceninja** [driftwoodinteractive/fmPDA#1]
We use a ton of PHP calls to a FileMaker script that does ExecuteSQL.  (This is a method that really speeds up finds with multiple records.)

We've been storing this information to a global text field and then grabbing the results from PHP.  We get an error about permissions.

**Comment by driftwoodinteractive** [comment]
You’re going to have to be a lot more specific about what your problem is. What kind of error message are you receiving? Is it being returned by an fmPDA method? Can you show a code example?

**Comment by workplaceninja** [comment]
I'll get you more details and an example on Monday, but it's probably a FileMaker error message passed back by the ExecuteScript command.  It can be as simple as running a FileMaker command, setting a "1" in a global text field, and then trying to get that "1" back from PHP.

**Comment by workplaceninja** [comment]
OK, scratch the part about the error - that was a user privileges thing.  We simply get back an empty string when doing a call to get the contents of the global text field.

Here's the idea:

--------------------
$findCommand = $fm->newFindAllCommand($layout);
$findCommand->setScript('Custom_Script',$q);
$result = $findCommand->execute();
			
if ($fm->isError($result)) {
    echo 'Error - ' . $result->getMessage();
} else {
    $records = $result->getRecords();
    echo $records[0]->getField('Global_Field');
}
--------------------

This works using the PHP API.  The script executed ("Custom_Script") stores its value into a global field, and so the contents of it get passed back into the record data.

Using fmPDA, we get an empty string back.  I looked at Data API documents, and to set a global field you need to use a different REST string.  I suspect that because of this, maybe the Data API separates all global fields from record data returned?  Not sure...

**Comment by workplaceninja** [comment]
Is there perhaps another way that I can get the script results from an executed script?  It looks like the Data API does return script results, but is there a way in this PHP library to do so?

**Comment by workplaceninja** [comment]
Actually it looks like both the global field contents and the script result come back through the $result, so I just need to point to it differently than I do with the regular PHP API.

**Comment by workplaceninja** [comment]
Ahh, I figured out what's going on.

Since the global field is actually a repetition field, getField() is requiring that I use Global_Field(1) rather than just Global_Field.  Perhaps getField() should be modified to look for the first repetition if not specified?

**Comment by workplaceninja** [comment]
I'll close this and open a new ticket about repetitions...
