### ISSUE TITLE
strftime deprecated in PHP 8.1

### ISSUE THREAD

**Issue by drewwesley** [driftwoodinteractive/fmPDA#11]
fmPDA/v1/fmLogger.class.php (line 122): strftime is deprecated in PHP 8.1
Simple Fix..

Changed:
$this->log  .= date('Y-m-d') .' '. strftime('%H:%M:%S') .' '. $this->convertToText($data) ."\n";
To:
$this->log  .= date('Y-m-d H:i:s')  .' '. $this->convertToText($data) ."\n";

As of this writing, tested with FileMaker Server 19.5.2, PHP 8.1.14

**Comment by driftwoodinteractive** [comment]
This is now fixed in the latest release.

**Comment by drewwesley** [comment]
Wow, thank you!!!
One thing I noticed about the code from earlier implementations was its 
commenting and structure.
Andrew

**Comment by driftwoodinteractive** [comment]
> Wow, thank you!!! One thing I noticed about the code from earlier implementations was its commenting and structure. Andrew
> […](#)

I hope that's a good thing :)
