### ISSUE TITLE
Function getLayout() returns NULL

### ISSUE THREAD

**Issue by Andreas-T** [driftwoodinteractive/fmPDA#13]
In the file fmResult.class.php the function getLayout returns NULL when called like this:

$layout = $fm->getLayout($layoutName);

I see that the getLayout() function does not accept the layout name as a parameter, like the FileMaker getLayout() function does.

**Comment by driftwoodinteractive** [comment]
This is unsupported as there is no way to do this with the Data API. If you call this method it returns NULL and outputs to the debug log:

   function getLayout($layout)
   {
      fmLogger('<br><br>*** getLayout is not supported. ***<br><br>');
      return NULL;
   }
