### ISSUE TITLE
Parameter declaration deprecated in PHP 8.1

### ISSUE THREAD

**Issue by Andreas-T** [driftwoodinteractive/fmPDA#14]
Deprecated: Optional parameter $params declared before required parameter $method is implicitly treated as a required parameter in fmPDA/v2/fmDataAPI.class.php on line 1155

**Comment by driftwoodinteractive** [comment]
This is now fixed in the latest release.

**Comment by driftwoodinteractive** [comment]
This is now fixed in the latest release.
