### ISSUE TITLE
Cannot do compound find

### ISSUE THREAD

**Issue by workplaceninja** [driftwoodinteractive/fmPDA#2]
When trying to add a request to a compound find, I get this error:

Fatal error: Uncaught Error: Call to undefined method fmFindQuery::getRequest() in /usr/share/nginx/html/fm/FMData/v2/_fmPDA/fmFindQuery.class.php:90 Stack trace: #0 /usr/share/nginx/html/fm/python/getActiveAssignmentsForArtistTest.php(33): fmFindQuery->add(1, Object(fmFindQuery)) #1 {main} thrown in /usr/share/nginx/html/fm/FMData/v2/_fmPDA/fmFindQuery.class.php on line 90

Works directly in the PHP API.

[getActiveAssignmentsForArtistTest.php.zip](https://github.com/driftwoodinteractive/fmPDA/files/4028543/getActiveAssignmentsForArtistTest.php.zip)

**Comment by workplaceninja** [comment]
This is using FileMaker 18v3 on a Windows 2016 server.  PHP 7.2.10 is hosted in CentOS 7.

**Comment by workplaceninja** [comment]
This happens any time I try to use:
$compoundFind->execute();

I'm assuming others have this issue too?

**Comment by fubizitch** [comment]
i get this issue too

**Comment by driftwoodinteractive** [comment]
Replace:
			$request[$x] = $fm->newFindCommand($layout);

with:
			$request[$x] = $fm->newFindRequest($layout);

A compound find expects a ‘Find Request’ object, not a ‘Find Command’ object. That’s what the internal FM documentation references. I’m surprised it your code worked in the ‘old’ CWP. If you make the suggested change to your code it will work.

You can also look at the example provided with fmPDA to see how it's done.

**Comment by fubizitch** [comment]
ah yes.  most of us rely on other user examples across the web because fm documentation on the api sucks.  it actually does work, maybe not by design though.

thanks for the info - will give it a try.

**Comment by driftwoodinteractive** [comment]
I know, the docs are scant and there's never been a lot of good examples. That's why I tried to provide at least a barebones example for all the variety of operations so you'd have something to test against.

**Comment by workplaceninja** [comment]
We really appreciate what you've done for getting us up and running quickly on the data API, Mark!

I made the change as suggested - newFindRequest.  Instead of a PHP error, now we're getting this FM error:

Error Code: 3, Error String: Malformed

The same code works when connecting to the PHP API, but not through FMPDA (latest).  Thoughts?

**Comment by driftwoodinteractive** [comment]
Can you post your code? I'm curious what you're doing...

**Comment by workplaceninja** [comment]
Hang on - this one might be an issue with our server...

**Comment by workplaceninja** [comment]
Works, thanks!
