### ISSUE TITLE
Unable to get data from repetition field

### ISSUE THREAD

**Issue by workplaceninja** [driftwoodinteractive/fmPDA#5]
When I try to get data from a repetition field from the results of a query, and I do not specify a repetition, I get an empty string.  When using the PHP API, I get data from the first repetition.

If repetition is unspecified, the getField() method should check to see if "field(1)" exists in the data results and get contents from that, otherwise grab data results from "field".

**Comment by driftwoodinteractive** [comment]
Fixed.

**Comment by workplaceninja** [comment]
Awesome, thank you!
