### ISSUE TITLE
Getting 2nd token in certain cases

### ISSUE THREAD

**Issue by laynebay** [driftwoodinteractive/fmPDA#6]
After initial auth to grab products for display, I get a token added to my session. All good.  Whenever I do some other calls such as add a request record or authenticate a user (table-based via script), I get a second token.  Any thoughts? See screenshot. Thanks.  I absolutely love this library!
<img width="1186" alt="2-tokens-fmPDA" src="https://user-images.githubusercontent.com/1091133/85339519-531fe900-b4b2-11ea-845a-a434cbf7ec34.png">

**Comment by driftwoodinteractive** [comment]
The define() for the token key was slightly different in v1 vs. v2 (I've fixed this in an upcoming release):

FM-Data-Session-Token
FM-Data-Session-token

However, is there a chance you're using both v1 and v2 in your include paths? That would account for this. If so, you could fix the paths yourself.

**Comment by laynebay** [comment]
Mark, You are right on!

In my Cart model - `require_once APPPATH .'/third_party/fmPDA/vLatest/fmPDA.php';`
In my Auth model- `require_once APPPATH .'/third_party/fmPDA/v1/fmPDA.php';`

I've been reusing (copying) models for a while across projects and I bet I had to use **vLatest** for something in one model that I didn't worry about in the other.

Thank you very much.  I thought it might be something simple, but I missed it.  I even started at both `FM-Data-Session-Token` and FM`-Data-Session-token` and didn't see it!

Cheers.
